openapi: 3.0.3
info:
  title: Easyapp API
  version: 1.0.0
  description: API documentation for easyapp
paths:
  /api/hello/:
    get:
      operationId: api_hello_retrieve
      description: Get a hello world message
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/register/:
    post:
      operationId: api_register_create
      description: Register a new member using in-memory store.
      tags:
      - api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/login/:
    post:
      operationId: api_login_create
      description: Obtain an access token for an existing member.
      tags:
      - api
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentials'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/profile/:
    get:
      operationId: api_profile_retrieve
      description: Get current authenticated member profile.
      tags:
      - api
      security:
      - TokenAuth: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        '401':
          description: Unauthorized
components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          maxLength: 200
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - message
      - timestamp
    Member:
      type: object
      properties:
        username:
          type: string
        created_at:
          type: string
          format: date-time
      required:
      - username
    AuthCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
          format: password
      required:
      - username
      - password
    AuthResponse:
      type: object
      properties:
        username:
          type: string
        token:
          type: string
      required:
      - username
      - token
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    TokenAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
